# 轉置矩陣

$$
matrix_a =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{pmatrix}
$$


$$
matrix_a^{T} =
\begin{pmatrix}
1 & 3 & 5\\
2 & 4 & 6
\end{pmatrix}
$$


In [9]:
matrix_a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

matrix_a.T

array([[1, 3, 5],
       [2, 4, 6]])

# matrix multiplication作業101:




$$
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{pmatrix}
\times
\begin{pmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{pmatrix}
=
\begin{pmatrix}
1*7+2*10 & 1*8+2*11 & 1*9+2*12 \\
 &  &  \\
 &  &
\end{pmatrix}
=
\begin{pmatrix}
27 & 30 & 33 \\
61 & 68 & 75 \\
95 & 106 & 117
\end{pmatrix}
$$


In [10]:
# Define the first matrix (3x2)
matrix_a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Define the second matrix (2x3)
matrix_b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)

# Perform matrix multiplication
result_matrix = matrix_a @ matrix_b

print("\nResult of Matrix A * Matrix B:")
print(result_matrix)
print(f"The shape of the result matrix is: {result_matrix.shape}")

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Result of Matrix A * Matrix B:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
The shape of the result matrix is: (3, 3)


# 矩陣運算 20 題題庫（Matrix Operations Question Bank）

#### 1️⃣ 矩陣加法

已知
$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$, $B=\begin{pmatrix} -1 & 0 \\ 5 & 2 \end{pmatrix}$
求：(1) $A + B$

#### 2️⃣ 矩陣減法

已知
$C=\begin{pmatrix} 2 & -3 \\ 4 & 1 \end{pmatrix}$, $D=\begin{pmatrix} 5 & 2 \\ -1 & 0 \end{pmatrix}$
求：(1) $C - D$

#### 3️⃣ 純量乘法

$A=\begin{pmatrix} 2 & -1 \\ 0 & 3 \end{pmatrix}$
求：(1) $-2A$

#### 4️⃣ 矩陣乘法（2$\times$2 $\times$ 2$\times$2）

$A=\begin{pmatrix} 1 & 3 \\ 2 & 4 \end{pmatrix}$
$B=\begin{pmatrix} 0 & 1 \\ 5 & -2 \end{pmatrix}$
求：(1) $AB$ (2) $BA$（若可乘）

#### 5️⃣ 矩陣乘法（2$\times$3 $\times$ 3$\times$2）

$A=\begin{pmatrix} 1 & 0 & 2 \\ -1 & 3 & 1 \end{pmatrix}$
$B=\begin{pmatrix} 2 & 1 \\ 0 & -1 \\ 4 & 3 \end{pmatrix}$
求：(1) $AB$

#### 6️⃣ 轉置運算

$A=\begin{pmatrix} 1 & -2 & 3 \\ 0 & 4 & -1 \end{pmatrix}$
求：(1) $A^T$

#### 7️⃣ 轉置與加法

$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$
$B=\begin{pmatrix} -1 & 0 \\ 2 & 1 \\ 3 & -2 \end{pmatrix}$
求：(1) $(A+B)^T$ (2) $A^T + B^T$ (3) 比較是否相等

#### 8️⃣ 行列式（2$\times$2）

$A=\begin{pmatrix} a & b \\ c & d \end{pmatrix}$
- (1) 列出$\det(A)$ 公式
- (2) 若$a=2, b=3, c=1, d=4$ 答案為何?

#### 9️⃣ 行列式（3$\times$3）

$A=\begin{pmatrix} 1 & 2 & 3 \\ 0 & -1 & 4 \\ 2 & 1 & 0 \end{pmatrix}$
求 $\det(A)$

#### 🔟 是否可逆？

$A=\begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$
求：(1) $\det(A)$ (2) 是否可逆

#### 1️⃣1️⃣ 2$\times$2 逆矩陣

$A=\begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix}$
求 $A^{-1}$

#### 1️⃣2️⃣ 3$\times$3 矩陣可逆判斷

$A=\begin{pmatrix} 1 & 0 & 2 \\ 0 & 1 & -1 \\ 1 & 2 & 0 \end{pmatrix}$
求：(1) 可逆與行列式關係 (2) $\det(A)$ (3) 求逆方法

#### 1️⃣3️⃣ 線性方程組矩陣形式

方程：$\begin{cases} x+2y=5 \\ 3x-y=4 \end{cases}$
求：(1) $AX=b$ (2) $A, X, b$

#### 1️⃣4️⃣ 用逆矩陣解方程組

$A=\begin{pmatrix} 1 & 2 \\ 3 & -1 \end{pmatrix}$, $b=\begin{pmatrix} 5 \\ 4 \end{pmatrix}$
求 $X=A^{-1}b$

#### 1️⃣5️⃣ 矩陣的秩

$A=\begin{pmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 1 & 1 & 1 \end{pmatrix}$
求：(1) rank 意義 (2) rank 判斷

#### 1️⃣6️⃣ 對稱矩陣判斷

(a) $\begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}$
(b) $\begin{pmatrix} 0 & 3 \\ -3 & 0 \end{pmatrix}$
(c) $\begin{pmatrix} 1 & 0 & 2 \\ 0 & 3 & 1 \\ 2 & 1 & 4 \end{pmatrix}$

#### 1️⃣7️⃣ 矩陣乘法可行性

A: $2\times3$, B: $3\times4$, C: $4\times1$
求：(1) 哪些乘積可行 (2) 結果維度

#### 1️⃣8️⃣ 單位矩陣乘法

$I_3=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$
$A=\begin{pmatrix} 2 & -1 & 0 \\ 0 & 3 & 1 \\ 1 & 0 & 4 \end{pmatrix}$
求 $AI_3, I_3A$

#### 1️⃣9️⃣ 特徵值

$A=\begin{pmatrix} 2 & 1 \\ 0 & 3 \end{pmatrix}$
求：(1) $\det(A-\lambda I)=0$ (2) 特徵值

#### 2️⃣0️⃣ 特徵向量

$A=\begin{pmatrix} 2 & 1 \\ 0 & 3 \end{pmatrix}$
求：(1) 特徵向量 (2) 驗證 $Av=\lambda v$

```latex
# 矩陣運算 20 題題庫（Matrix Operations Question Bank）

## 1️⃣ 矩陣加法

已知
$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$, $B=\begin{pmatrix} -1 & 0 \\ 5 & 2 \end{pmatrix}$
求：(1) $A + B$

## 2️⃣ 矩陣減法

已知
$C=\begin{pmatrix} 2 & -3 \\ 4 & 1 \end{pmatrix}$, $D=\begin{pmatrix} 5 & 2 \\ -1 & 0 \end{pmatrix}$
求：(1) $C - D$

## 3️⃣ 純量乘法

$A=\begin{pmatrix} 2 & -1 \\ 0 & 3 \end{pmatrix}$
求：(1) $-2A$

## 4️⃣ 矩陣乘法（2$\times$2 $\times$ 2$\times$2）

$A=\begin{pmatrix} 1 & 3 \\ 2 & 4 \end{pmatrix}$
$B=\begin{pmatrix} 0 & 1 \\ 5 & -2 \end{pmatrix}$
求：(1) $AB$ (2) $BA$（若可乘）

## 5️⃣ 矩陣乘法（2$\times$3 $\times$ 3$\times$2）

$A=\begin{pmatrix} 1 & 0 & 2 \\ -1 & 3 & 1 \end{pmatrix}$
$B=\begin{pmatrix} 2 & 1 \\ 0 & -1 \\ 4 & 3 \end{pmatrix}$
求：(1) $AB$

## 6️⃣ 轉置運算

$A=\begin{pmatrix} 1 & -2 & 3 \\ 0 & 4 & -1 \end{pmatrix}$
求：(1) $A^T$

## 7️⃣ 轉置與加法

$A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$
$B=\begin{pmatrix} -1 & 0 \\ 2 & 1 \\ 3 & -2 \end{pmatrix}$
求：(1) $(A+B)^T$ (2) $A^T + B^T$ (3) 比較是否相等

## 8️⃣ 行列式（2$\times$2）

$A=\begin{pmatrix} a & b \\ c & d \end{pmatrix}$
(1) $\det(A)$ 公式
(2) $a=2, b=3, c=1, d=4$

## 9️⃣ 行列式（3$\times$3）

$A=\begin{pmatrix} 1 & 2 & 3 \\ 0 & -1 & 4 \\ 2 & 1 & 0 \end{pmatrix}$
求 $\det(A)$

## 🔟 是否可逆？

$A=\begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$
求：(1) $\det(A)$ (2) 是否可逆

## 1️⃣1️⃣ 2$\times$2 逆矩陣

$A=\begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix}$
求 $A^{-1}$

## 1️⃣2️⃣ 3$\times$3 矩陣可逆判斷

$A=\begin{pmatrix} 1 & 0 & 2 \\ 0 & 1 & -1 \\ 1 & 2 & 0 \end{pmatrix}$
求：(1) 可逆與行列式關係 (2) $\det(A)$ (3) 求逆方法

## 1️⃣3️⃣ 線性方程組矩陣形式

方程：$\begin{cases} x+2y=5 \\ 3x-y=4 \end{cases}$
求：(1) $AX=b$ (2) $A, X, b$

## 1️⃣4️⃣ 用逆矩陣解方程組

$A=\begin{pmatrix} 1 & 2 \\ 3 & -1 \end{pmatrix}$, $b=\begin{pmatrix} 5 \\ 4 \end{pmatrix}$
求 $X=A^{-1}b$

## 1️⃣5️⃣ 矩陣的秩

$A=\begin{pmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 1 & 1 & 1 \end{pmatrix}$
求：(1) rank 意義 (2) rank 判斷

## 1️⃣6️⃣ 對稱矩陣判斷

(a) $\begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}$
(b) $\begin{pmatrix} 0 & 3 \\ -3 & 0 \end{pmatrix}$
(c) $\begin{pmatrix} 1 & 0 & 2 \\ 0 & 3 & 1 \\ 2 & 1 & 4 \end{pmatrix}$

## 1️⃣7️⃣ 矩陣乘法可行性

A: $2\times3$, B: $3\times4$, C: $4\times1$
求：(1) 哪些乘積可行 (2) 結果維度

## 1️⃣8️⃣ 單位矩陣乘法

$I_3=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$
$A=\begin{pmatrix} 2 & -1 & 0 \\ 0 & 3 & 1 \\ 1 & 0 & 4 \end{pmatrix}$
求 $AI_3, I_3A$

## 1️⃣9️⃣ 特徵值

$A=\begin{pmatrix} 2 & 1 \\ 0 & 3 \end{pmatrix}$
求：(1) $\det(A-\lambda I)=0$ (2) 特徵值

## 2️⃣0️⃣ 特徵向量

$A=\begin{pmatrix} 2 & 1 \\ 0 & 3 \end{pmatrix}$
求：(1) 特徵向量 (2) 驗證 $Av=\lambda v$
```